// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: splab_grpc_service.proto

#include "splab_grpc_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace splab_grpc_service {
}  // namespace splab_grpc_service
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_splab_5fgrpc_5fservice_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_splab_5fgrpc_5fservice_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_splab_5fgrpc_5fservice_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_splab_5fgrpc_5fservice_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_splab_5fgrpc_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030splab_grpc_service.proto\022\022splab_grpc_s"
  "ervice\032\033google/protobuf/empty.proto2V\n\024S"
  "PLabRenderingServer\022>\n\ninitServer\022\026.goog"
  "le.protobuf.Empty\032\026.google.protobuf.Empt"
  "y\"\000B\010\242\002\005SPLABb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_splab_5fgrpc_5fservice_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_splab_5fgrpc_5fservice_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_splab_5fgrpc_5fservice_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_splab_5fgrpc_5fservice_2eproto = {
  false, false, descriptor_table_protodef_splab_5fgrpc_5fservice_2eproto, "splab_grpc_service.proto", 181,
  &descriptor_table_splab_5fgrpc_5fservice_2eproto_once, descriptor_table_splab_5fgrpc_5fservice_2eproto_sccs, descriptor_table_splab_5fgrpc_5fservice_2eproto_deps, 0, 1,
  schemas, file_default_instances, TableStruct_splab_5fgrpc_5fservice_2eproto::offsets,
  file_level_metadata_splab_5fgrpc_5fservice_2eproto, 0, file_level_enum_descriptors_splab_5fgrpc_5fservice_2eproto, file_level_service_descriptors_splab_5fgrpc_5fservice_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_splab_5fgrpc_5fservice_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_splab_5fgrpc_5fservice_2eproto)), true);
namespace splab_grpc_service {

// @@protoc_insertion_point(namespace_scope)
}  // namespace splab_grpc_service
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
