#!/usr/bin/env python
import platform

current_os = platform.system()

Import("env")

env.add_source_files(env.servers_sources, "*.cpp")


if current_os == "Windows":
    vcpkg_root = 'C:\\Users\\play1\\Documents\\GitHub\\vcpkg\\installed\\x86-windows' # change at other systems
    vcpkg_include = "{}\\include".format(vcpkg_root)
    env.Append(CPPPATH=[vcpkg_include]) # yjkim

else: # mac or linux
    env.Append(CPPPATH=["/usr/local/include"]) # yjkim
    env.Append(LIBPATH=['/usr/local/lib'])
    env.Append(LIBS=["protobuf", "grpc", "grpc++"])

SConscript("renderer_rd/SCsub")
SConscript("splab/SCsub")

