#!/usr/bin/env python

Import("env")

if env["platform"] in ["haiku", "osx", "windows", "x11"]:
    # Thirdparty source files
    thirdparty_dir = "#thirdparty/glremote/"
    thirdparty_sources = [
        "glremote.cpp",
    ]
    thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

    env.Prepend(CPPPATH=[thirdparty_dir])

    # env.Append(CPPDEFINES=["GLAD_ENABLED"])
    # env.Append(CPPDEFINES=["GLES_OVER_GL"])
    env.Append(CPPDEFINES=["GLREMOTE"])

    env_thirdparty = env.Clone()
    env_thirdparty.disable_warnings()
    env_thirdparty.add_source_files(env.drivers_sources, thirdparty_sources)

env.Append(CPPPATH=["/usr/include"])
env.Append(LIBPATH=["/usr/lib"])

env.Append(LIBS=["zmq"])

# Godot source files
env.add_source_files(env.drivers_sources, "*.cpp")
