#!/usr/bin/env python

Import("env")

env.add_source_files(env.servers_sources, "*.cpp")
env.add_source_files(env.servers_sources, "*.cc")
env.Append(LIBPATH=['/usr/local/lib'])
env.Append(LIBS=["protobuf", "grpc", "grpc++"])
# env.Append(CXXFLAGS=["-framework"])