// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: splab_grpc_service.proto

#include "splab_grpc_service.pb.h"
#include "splab_grpc_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace splab_grpc_service {

static const char* SPLabRenderingServer_method_names[] = {
  "/splab_grpc_service.SPLabRenderingServer/SayHello",
};

std::unique_ptr< SPLabRenderingServer::Stub> SPLabRenderingServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SPLabRenderingServer::Stub> stub(new SPLabRenderingServer::Stub(channel));
  return stub;
}

SPLabRenderingServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayHello_(SPLabRenderingServer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SPLabRenderingServer::Stub::SayHello(::grpc::ClientContext* context, const ::splab_grpc_service::HelloRequest& request, ::splab_grpc_service::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::splab_grpc_service::HelloRequest, ::splab_grpc_service::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void SPLabRenderingServer::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::splab_grpc_service::HelloRequest* request, ::splab_grpc_service::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::splab_grpc_service::HelloRequest, ::splab_grpc_service::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void SPLabRenderingServer::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::splab_grpc_service::HelloRequest* request, ::splab_grpc_service::HelloReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::splab_grpc_service::HelloReply>* SPLabRenderingServer::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::splab_grpc_service::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::splab_grpc_service::HelloReply, ::splab_grpc_service::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::splab_grpc_service::HelloReply>* SPLabRenderingServer::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::splab_grpc_service::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

SPLabRenderingServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SPLabRenderingServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SPLabRenderingServer::Service, ::splab_grpc_service::HelloRequest, ::splab_grpc_service::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SPLabRenderingServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::splab_grpc_service::HelloRequest* req,
             ::splab_grpc_service::HelloReply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
}

SPLabRenderingServer::Service::~Service() {
}

::grpc::Status SPLabRenderingServer::Service::SayHello(::grpc::ServerContext* context, const ::splab_grpc_service::HelloRequest* request, ::splab_grpc_service::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace splab_grpc_service

